name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run package:${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: product-scanner-${{ matrix.platform }}
          path: release/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Product Scanner ${{ github.ref_name }}
            
            ### Downloads:
            - **macOS**: Download the `.dmg` file
            - **Windows**: Download the `.exe` installer
            - **Linux**: Download the `.AppImage` file
            
            ### Installation:
            1. Download the appropriate file for your operating system
            2. Install/run the application
            3. On first launch, select a folder where your CSV files will be saved
            4. Start scanning products!
          draft: false
          prerelease: false 